"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ayjuo3b9k(6py%zaq(5hctdpjlf8^wha0(o)2)p5@ewzo+zh2k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'authentication',
    'appointments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# Database Configuration
if 'RDS_HOSTNAME' in os.environ:
    # Production - RDS PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('RDS_DB_NAME', 'secureflow_db'),
            'USER': os.environ.get('RDS_USERNAME', 'secureflow_admin'),
            'PASSWORD': os.environ.get('RDS_PASSWORD', 'SecureFlow2024!'),
            'HOST': os.environ.get('RDS_HOSTNAME', 'secureflow-db.cmbq2wmicc2v.us-east-1.rds.amazonaws.com'),
            'PORT': os.environ.get('RDS_PORT', '5432'),
        }
    }
else:
    # Fallback - Hardcoded PostgreSQL for AWS
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'secureflow_db',
            'USER': 'secureflow_admin',
            'PASSWORD': 'SecureFlow2024!',
            'HOST': 'secureflow-db.cmbq2wmicc2v.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = []
# Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Session Settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# AWS Configuration
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = config('AWS_REGION', default='us-east-1')
AWS_SQS_QUEUE_URL = config('AWS_SQS_QUEUE_URL', default='')

# External Service URLs
OTP_SERVICE_URL = config(
    'OTP_SERVICE_URL', default='https://plx61avh5f.execute-api.us-east-1.amazonaws.com/prod')
EMAIL_SERVICE_URL = config(
    'EMAIL_SERVICE_URL', default='https://2rsma0i53j.execute-api.us-east-1.amazonaws.com/prod/api/send/')
PDF_SERVICE_URL = config(
    'PDF_SERVICE_URL', default='https://rz27c392l4.execute-api.us-east-1.amazonaws.com/html/pdf')
APPOINTMENT_SERVICE_URL = config(
    'APPOINTMENT_SERVICE_URL', default='https://2o7jj4hez6.execute-api.us-east-1.amazonaws.com')
APPOINTMENT_API_KEY = config('APPOINTMENT_API_KEY', default='')

HEALTHCARE_PROVIDER_ID = config('HEALTHCARE_PROVIDER_ID', default='', cast=str)
LEGAL_PROVIDER_ID = config('LEGAL_PROVIDER_ID', default='', cast=str)
CONSULTANCY_PROVIDER_ID = config(
    'CONSULTANCY_PROVIDER_ID', default='', cast=str)

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/appointments/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ZAP SECURITY
# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net",
                  "https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net",
                 "https://cdnjs.cloudflare.com", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https://cdn.jsdelivr.net")

# Additional Security
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = False  # Set to True when using HTTPS

# Permissions Policy
PERMISSIONS_POLICY = {
    "geolocation": [],
    "microphone": [],
    "camera": [],
}
